server:
  port: 8081
spring:
  application:
    name: "VideogamesTournamentManagement"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: "https://idp.example.com/issuer"
          client-id: "myclientid"
tournament:
  max-mods: 2
  max-free-tournaments: 2
jwt:
  json-exp-roles: "/roles"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

driven-adapter:
  airtable:
    base-url: "https://api.airtable.com/v0"
    user:
      base-path:
      bearer:
    transaction:
      base-path:
      bearer:
    tournament:
      base-path:
      bearer:
    ticket:
      base-path:
      bearer:
    reward:
      base-path:
      bearer:
    registration:
      base-path:
      bearer:
    match:
      base-path:
      bearer:
    game:
      base-path:
      bearer:
    donation:
      base-path:
      bearer:
  qr:
    base-url: https://api.qrserver.com/v1/create-qr-code/